@url = http://192.168.195.88:80

###
GET {{url}} HTTP/1.1

###
# @name loginAdmin
POST {{url}}/authorize HTTP/1.1
Content-Type: application/json

{
    "client_id":"foo",
    "client_secret":"bar"

}

###
@token = {{loginAdmin.response.body.access_token}}
GET {{url}}/protected HTTP/1.1
Authorization: Bearer {{token}}
